name: Build and push Docker image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set release date
        run: |
          echo "RELEASE_DATE=$(date +%y.%m.%d)" >> ${GITHUB_ENV}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: registry.cn-hangzhou.aliyuncs.com

      -
        name: Build and push
        uses: docker/build-push-action@v4

        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_NAMESPACE }}/chuanghu-chatgpt:latest
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKERHUB_NAMESPACE }}/chuanghu-chatgpt:${{ env.RELEASE_DATE }}